version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: AWS configure
          command: |
            aws configure list
      - run: 
          name: Zip and push Lambda to S3 Bucket
          command: |
            zip -r lambda.zip index.js
            aws s3 cp lambda.zip s3://vishaka-serverless-lambda-function/

workflows:
  version: 2

  lambda_buid:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master